jobs:
  - job: build
    displayName: Build
    steps:
      - script: |
          yarn install
        displayName: Install dependencies

      - script: |
          yarn lint
        displayName: Lint

      - script: |
          yarn test
        displayName: Run tests

      - script: |
          yarn build
        displayName: Build

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        displayName: Publish test results
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: "**/junit.xml"

      - task: PublishCodeCoverageResults@1
        displayName: Publish code coverage
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: "$(Build.Repository.LocalPath)/coverage/cobertura-coverage.xml"
          reportDirectory: "$(Build.Repository.LocalPath)/coverage"
          failIfCoverageEmpty: true
